//
//  AddInteractor.swift
//  ViperTaskManager
//
//  Created by Aaron Lee on 19/02/16.
//  Copyright © 2016 One Fat Giraffe. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import Foundation


protocol AddInteractorInputProtocol: class {
    
    weak var presenter: AddInteractorOutputProtocol! { get set }

//    func getCitiesWithName(name: String)
//    func saveProject(project: Project)
    func updateProject(project: Project, callback: (result: Project?, error: NSError?) -> ())
    func updateProjectInPersistentStore(project: Project)
    func fetchSortBy(projectId: String, callback: (result: String) -> ())
}

protocol AddInteractorOutputProtocol: class {
   
//    func foundCities(tasks: [Task])
}

class AddInteractor {

    weak var presenter: AddInteractorOutputProtocol!
    
    var dataManager: AddDataManagerInputProtocol!
}

extension AddInteractor: AddInteractorInputProtocol {
    
//    func getCitiesWithName(name: String) {
//        self.dataManager.fetchCitiesWithName(name) { [weak self] (tasks) -> () in
//            self?.presenter.foundCities(tasks)
//        }
//    }
    
    func saveTask(task: Task) {
        self.dataManager.saveTaskToPersistentStore(task)
    }
    
    func updateProject(project: Project, callback: (result: Project?, error: NSError?) -> ()) {
        self.dataManager.updateProject(project) { (result, error) in
            callback(result: result, error: error)
        }
    }
    
    func updateProjectInPersistentStore(project: Project) {
        self.dataManager.updateProjectInPersistentStore(project)
    }
    
    func fetchSortBy(projectId: String, callback: (result: String) -> ()) {
        self.dataManager.fetchProjectFromPersistentStore(projectId) { result in
            callback(result: result.sortBy)
        }
    }
}

extension AddInteractor: AddDataManagerOutputProtocol {
    
}
