//
//  AddPresenter.swift
//  ViperTaskManager
//
//  Created by Aaron Lee on 19/02/16.
//  Copyright © 2016 One Fat Giraffe. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import UIKit


protocol AddViewControllerDelegate: class {
    
    func addViewControllerDidSelectProject(project: Project)
}

protocol AddPresenterProtocol: class {

    weak var delegate: AddViewControllerDelegate? { get set }
    
    func done()
    func fetchTasks(projectId: String, callback: (result: [Task]?) -> ())
    func selectTask(task: Task)
    func createTask(projectId: Int, callback: ([Task]) -> ())
    func updateProject(project: Project, callback: (result: Project?, error: NSError?) -> ())
    func updateProjectInPersistentStore(project: Project)
    func fetchSortBy(projectId: String, callback: (result: String) -> ())
    
    func addNewTask(projectId: String, title: String)
    func removeTask(task: Task, callback: (error: NSError?) -> ())
}

protocol AddInterfaceProtocol: class {
    
    var presenter: AddPresenterProtocol!  { get set }

}

class AddPresenter {

	weak private var interface: AddInterfaceProtocol!
	private let interactor: AddInteractorInputProtocol
    private let router: AddRouterInputProtocol

    weak var delegate: AddViewControllerDelegate?

    
    init(interface: AddInterfaceProtocol, interactor: AddInteractorInputProtocol, router: AddRouterInputProtocol) {
        self.interface = interface
        self.interactor = interactor
        self.router = router
    }
}

extension AddPresenter: AddPresenterProtocol {
    
    func done() {
        self.router.closeAddViewController(viewController: self.interface as! UIViewController)
    }
    
    func fetchTasks(projectId: String, callback: (result: [Task]?) -> ()) {
        self.interactor.fetchTasks(projectId) { (result) in
            callback(result: result)
        }
    }
    
    func selectTask(task: Task) {
        self.router.presentDetailViewController(fromViewController: self.interface as! UIViewController, task: task)
    }
    
    func createTask(projectId: Int, callback: ([Task]) -> ()) {
        self.router.closeAddViewController(viewController: interface as! UIViewController)
    }
    
    func updateProject(project: Project, callback: (result: Project?, error: NSError?) -> ()) {
        self.interactor.updateProject(project) { (result, error) in
            callback(result: result, error: error)
        }
    }
    
    func updateProjectInPersistentStore(project: Project) {
        self.interactor.updateProjectInPersistentStore(project)
    }
    
    func fetchSortBy(projectId: String, callback: (result: String) -> ()) {
        self.interactor.fetchSortBy(projectId) { (result) in
            callback(result: result)
        }
    }
    
    func addNewTask(projectId: String, title: String) {
        self.interactor.createTask(projectId, title: title) { (result, error) -> Void in
            if (error != nil) {
                print("error what")
            } else {
                self.router.presentDetailViewController(fromViewController: self.interface as! UIViewController, task: result!)
            }
        }
    }
    
    func removeTask(task: Task, callback: (error: NSError?) -> ()) {
        self.interactor.removeTask(task) { (error) in
            callback(error: error)
        }
    }
}

extension AddPresenter: AddInteractorOutputProtocol {

}
