//
//  AddRouter.swift
//  ViperTaskManager
//
//  Created by Aaron Lee on 19/02/16.
//  Copyright © 2016 One Fat Giraffe. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import UIKit

protocol AddRouterInputProtocol: class {
    func closeAddViewController(viewController viewController: UIViewController)
}

protocol AddParentRouterProtocol: class {
    
}

class AddRouter: AddRouterInputProtocol {

    func closeAddViewController(viewController viewController: UIViewController) {
        let idiom = UIDevice.currentDevice().userInterfaceIdiom
        switch idiom {
        case .Phone:
            viewController.navigationController!.dismissViewControllerAnimated(true, completion: nil)

        case .Pad:
            viewController.navigationController!.popViewControllerAnimated(true)
            
        default:
            fatalError("Device is not supported yet")
        }
    }
}
