//
//  AddRouter.swift
//  ViperTaskManager
//
//  Created by Aaron Lee on 19/02/16.
//  Copyright © 2016 One Fat Giraffe. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import UIKit

protocol AddRouterInputProtocol: class {
    func closeAddViewController(viewController: UIViewController)
    func presentDetailViewController(fromViewController: UIViewController, task: Task)
    
    var detailAssembler: DetailAssembler! { get set }
}

protocol AddParentRouterProtocol: class {
    
}

class AddRouter: AddRouterInputProtocol {

    var detailAssembler: DetailAssembler!
    
    func closeAddViewController(viewController: UIViewController) {
        let idiom = UIDevice.current.userInterfaceIdiom
        switch idiom {
        case .phone:
            viewController.navigationController!.dismiss(animated: true, completion: nil)

        case .pad:
            viewController.navigationController!.popViewController(animated: true)
            
        default:
            fatalError("Device is not supported yet")
        }
    }
    
    func presentDetailViewController(fromViewController: UIViewController, task: Task) {
        detailAssembler.presentDetailViewController(fromViewController: fromViewController, task: task)
    }
}
