//
//  RootInteractor.swift
//  ViperTaskManager
//
//  Created by Aaron Lee on 20/02/16.
//  Copyright © 2016 One Fat Giraffe. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import Foundation

protocol RootInteractorInputProtocol: class {
    var presenter: RootInteractorOutputProtocol! { get set }
}

protocol RootInteractorOutputProtocol: class {
    
}

class RootInteractor {
    weak var presenter: RootInteractorOutputProtocol!
}

extension RootInteractor: RootInteractorInputProtocol {
    
}
