//
//  ServiceLocatorAssembler.swift
//  ViperTaskManager
//
//  Created by Aaron Lee on 24/02/16.
//  Copyright © 2016 One Fat Giraffe. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import Foundation
import Swinject

class ServiceLocatorAssembler {
    let assembler: Assembler
    
    init() {
        let container = Container(parent: nil)
//        super.init(container: container)
//        self.applyAssembly(ServiceLocatorContainer())
        assembler = Assembler(container: container)
        assembler.apply(assembly: ServiceLocatorContainer())
    }
    
}
